const mongoose = require('mongoose');

const proposalLogSchema = new mongoose.Schema({
    productName: {
        type: String,
        required: true
    },
    sustainabilityFilters: {
        type: [String], // This defines an array of strings
        required: true
    },
    proposalText: {
        type: String, // This will store the long email generated by Gemini
        required: true
    },
    createdAt: {
        type: Date,
        default: Date.now
    }
});

module.exports = mongoose.model('ProposalLog', proposalLogSchema);